[package]
name = "virolution"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "virolution"
path = "src/main.rs"

[lib]
name = "virolution"
path = "src/lib.rs"

[dependencies]
csv = "1.1.6"
derivative = "2.2.0"
derive_more = "0.99.17"
phf = { version = "0.10", features = ["macros"] }
rand = { version = "0.8.5", features = ["alloc"] }
rand_distr = "0.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
seq_io = "0.3.1"
rayon = "1.5"
clap = { version = "3.1.18", features = ["derive"] }
itertools = "0.10.3"

[build-dependencies]
clap = { version = "3.1.18", features = ["derive"] }
clap_complete = "3.1.4"

[dev-dependencies]
serial_test = "0.6.0"
