[package]
name = "virolution"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "virolution"
path = "src/main.rs"

[lib]
name = "virolution"
path = "src/lib.rs"

[dependencies]
csv = "1.1.6"
derivative = "2.2.0"
phf = { version = "0.10", features = ["macros"] }
rand = { version = "0.8.5", features = ["alloc"] }
rand_distr = "0.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
rayon = "1.5"
