[package]
name = "virolution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
rand = { version = "0.8.5", features = ["alloc"] }
rand_distr = "0.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
rayon = "1.5"
